# EU AI Act Art. 52 — AI-Generated Content
# Generated by: GitHub Copilot   Template date: 2025-10-03
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)

from dagster import asset, AssetExecutionContext, MetadataValue
import requests
import json
import pathlib
import datetime as dt


@asset(group_name="graphql_crawl")
def fetch_countries_countries(context: AssetExecutionContext) -> str:
    url = "https://countries.trevorblades.com/"
    query = "{ countries { code name capital } }"
    r = requests.post(url, json={"query": query}, timeout=60)
    r.raise_for_status()
    items = r.json()["data"]["countries"]

    out = pathlib.Path("warehouse/oso_dagster/tmp/countries/countries")
    out.mkdir(parents=True, exist_ok=True)
    fp = out / f"{dt.date.today().isoformat()}.json"
    fp.write_text(json.dumps(items))

    context.add_output_metadata({
        "rows": MetadataValue.int(len(items)),
        "path": MetadataValue.path(str(fp)),
    })
    return str(fp)
