"""pr-agent CLI — scaffold new ingest asset files."""

import datetime as dt
import pathlib
import re
import sys

import click

# ---------------------------------------------------------------------------
# Shared header
# ---------------------------------------------------------------------------

_HEADER = """\
# EU AI Act Art. 52 — AI-Generated Content
# Generated by: pr-agent scaffold   Date: {date}
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)
"""

# ---------------------------------------------------------------------------
# Plain Python templates (default — no pipeline framework required)
# ---------------------------------------------------------------------------

_PLAIN_REST_TEMPLATE = _HEADER + """
from pr_automation_agent import BaseRestFetcher
import requests


class _{cls}(BaseRestFetcher):
    provider = "{provider}"
    entity = "{entity}"

    def fetch_all(self) -> list[dict]:
        # TODO: replace with your real endpoint and auth headers
        r = requests.get(
            "https://api.{provider}.com/{entity}",
            timeout=60,
            # headers={{"Authorization": "Bearer <token>"}},
        )
        r.raise_for_status()
        return r.json()  # TODO: adapt to actual response shape


def fetch_{provider}_{entity}() -> str:
    \"\"\"Fetch {entity} from {provider} and write to disk. Returns the output path.\"\"\"
    path, rows = _{cls}().run()
    print(f"Wrote {{rows}} rows to {{path}}")
    return path


if __name__ == "__main__":
    fetch_{provider}_{entity}()
"""

_PLAIN_GRAPHQL_TEMPLATE = _HEADER + """
from pr_automation_agent import BaseGraphQLFetcher


class _{cls}(BaseGraphQLFetcher):
    provider = "{provider}"
    entity = "{entity}"
    url = "https://api.{provider}.com/graphql"  # TODO: update URL
    query = \"\"\"
        {{
            {entity}(first: 100) {{
                nodes {{ id name }}            # TODO: match your schema
            }}
        }}
    \"\"\"

    def extract_records(self, data: dict) -> list[dict]:
        # TODO: update this path to match your GraphQL response
        return data["{entity}"]["nodes"]


def fetch_{provider}_{entity}() -> str:
    \"\"\"Fetch {entity} from {provider} GraphQL API and write to disk. Returns the output path.\"\"\"
    path, rows = _{cls}().run()
    print(f"Wrote {{rows}} rows to {{path}}")
    return path


if __name__ == "__main__":
    fetch_{provider}_{entity}()
"""

_PLAIN_DB_TEMPLATE = _HEADER + """
from pr_automation_agent import BaseDbReplicator, DevEnvSecretResolver


class _{cls}(BaseDbReplicator):
    engine_name = "{engine}"
    table = "{table}"

    def get_query(self, since: str) -> str:
        # TODO: update watermark column name if not updated_at
        return "SELECT * FROM {table} WHERE updated_at >= :since"


def replicate_{engine}_{table}() -> str:
    \"\"\"Replicate {table} incrementally and write Parquet to disk. Returns the output path.

    Reads PR_AGENT__{engine_upper}__URI and PR_AGENT__{engine_upper}__SINCE from env,
    or pass a custom resolver: {cls}(my_resolver).run()
    \"\"\"
    path, rows = _{cls}().run()
    print(f"Wrote {{rows}} rows to {{path}}")
    return path


if __name__ == "__main__":
    replicate_{engine}_{table}()
"""

# ---------------------------------------------------------------------------
# Dagster templates (--framework dagster)
# ---------------------------------------------------------------------------

_DAGSTER_REST_TEMPLATE = _HEADER + """
from dagster import asset, AssetExecutionContext
from pr_automation_agent.integrations.dagster import BaseRestAsset
import requests


class _{cls}(BaseRestAsset):
    provider = "{provider}"
    entity = "{entity}"

    def fetch_all(self) -> list[dict]:
        # TODO: replace with your real endpoint and auth headers
        r = requests.get(
            "https://api.{provider}.com/{entity}",
            timeout=60,
            # headers={{"Authorization": "Bearer <token>"}},
        )
        r.raise_for_status()
        return r.json()  # TODO: adapt to actual response shape


@asset(group_name="rest_crawl")
def fetch_{provider}_{entity}(context: AssetExecutionContext) -> str:
    return _{cls}().materialize(context)
"""

_DAGSTER_GRAPHQL_TEMPLATE = _HEADER + """
from dagster import asset, AssetExecutionContext
from pr_automation_agent.integrations.dagster import BaseGraphQLAsset


class _{cls}(BaseGraphQLAsset):
    provider = "{provider}"
    entity = "{entity}"
    url = "https://api.{provider}.com/graphql"  # TODO: update URL
    query = \"\"\"
        {{
            {entity}(first: 100) {{
                nodes {{ id name }}            # TODO: match your schema
            }}
        }}
    \"\"\"

    def extract_records(self, data: dict) -> list[dict]:
        # TODO: update this path to match your GraphQL response
        return data["{entity}"]["nodes"]


@asset(group_name="graphql_crawl")
def fetch_{provider}_{entity}(context: AssetExecutionContext) -> str:
    return _{cls}().materialize(context)
"""

_DAGSTER_DB_TEMPLATE = _HEADER + """
from dagster import asset, AssetExecutionContext
from pr_automation_agent.integrations.dagster import BaseDbReplicationAsset


class _{cls}(BaseDbReplicationAsset):
    engine_name = "{engine}"
    table = "{table}"

    def get_query(self, since: str) -> str:
        # TODO: update watermark column name if not updated_at
        return "SELECT * FROM {table} WHERE updated_at >= :since"


@asset(group_name="db_replication", required_resource_keys={{"secret_resolver"}})
def replicate_{engine}_{table}(context: AssetExecutionContext) -> str:
    return _{cls}().materialize(context)
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _to_class_name(*parts: str) -> str:
    return "".join(p.capitalize() for p in parts)


def _safe_id(value: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", value.lower())


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


@click.group()
@click.version_option(package_name="pr-automation-agent")
def cli():
    """pr-automation-agent — scaffold EU AI Act-compliant ingest asset files."""


@cli.command()
@click.argument("asset_type", metavar="TYPE", type=click.Choice(["rest", "graphql", "db"]))
@click.option("--provider", default=None, help="Provider name, e.g. stripe, github (rest/graphql)")
@click.option("--entity", help="Entity/resource name, e.g. invoices, issues (rest/graphql)")
@click.option("--engine", help="DB engine name, e.g. postgres, mysql (db only)")
@click.option("--table", help="Table name (db only)")
@click.option(
    "--framework",
    default=None,
    type=click.Choice(["dagster"]),
    help="Pipeline framework. Omit for plain Python (works with any framework or none).",
)
@click.option(
    "--output-dir",
    default=".",
    show_default=True,
    help="Directory to write the generated file into",
)
@click.option("--dry-run", is_flag=True, help="Print the generated file without writing it")
def scaffold(asset_type, provider, entity, engine, table, framework, output_dir, dry_run):
    """Generate a new ingest asset file.

    \b
    Plain Python (works with any framework or none):
      pr-agent scaffold rest    --provider stripe  --entity invoices
      pr-agent scaffold graphql --provider github  --entity issues
      pr-agent scaffold db      --engine postgres  --table orders

    \b
    Dagster:
      pr-agent scaffold rest    --provider stripe  --entity invoices  --framework dagster
      pr-agent scaffold db      --engine postgres  --table orders     --framework dagster
    """
    today = dt.date.today().isoformat()

    if asset_type in ("rest", "graphql"):
        if not provider:
            raise click.UsageError("--provider is required for rest and graphql types.")
        if not entity:
            raise click.UsageError("--entity is required for rest and graphql types.")
        provider = _safe_id(provider)
        entity = _safe_id(entity)
        cls = _to_class_name(provider, entity)

        if asset_type == "rest":
            tmpl = _DAGSTER_REST_TEMPLATE if framework == "dagster" else _PLAIN_REST_TEMPLATE
            code = tmpl.format(date=today, cls=cls, provider=provider, entity=entity)
            rel_path = pathlib.Path("rest") / provider / f"{entity}_asset.py"
        else:
            tmpl = _DAGSTER_GRAPHQL_TEMPLATE if framework == "dagster" else _PLAIN_GRAPHQL_TEMPLATE
            code = tmpl.format(date=today, cls=cls, provider=provider, entity=entity)
            rel_path = pathlib.Path("graphql") / provider / f"{entity}_asset.py"

    else:  # db
        if not engine:
            raise click.UsageError("--engine is required for db type.")
        if not table:
            raise click.UsageError("--table is required for db type.")
        engine = _safe_id(engine)
        table = _safe_id(table)
        cls = _to_class_name(engine, table)

        tmpl = _DAGSTER_DB_TEMPLATE if framework == "dagster" else _PLAIN_DB_TEMPLATE
        code = tmpl.format(
            date=today, cls=cls, engine=engine, table=table,
            engine_upper=engine.upper(),
        )
        rel_path = pathlib.Path("db") / engine / f"{table}_replication_asset.py"

    output_root = pathlib.Path(output_dir).resolve()

    if dry_run:
        click.echo(f"# Would write to: {output_root / rel_path}\n")
        click.echo(code)
        return

    dest = output_root / rel_path
    dest.parent.mkdir(parents=True, exist_ok=True)

    # Create __init__.py in output_root and every subdirectory up to dest
    for parent in reversed([output_root] + [p for p in dest.parents if output_root in p.parents]):
        init = parent / "__init__.py"
        if not init.exists():
            init.touch()

    if dest.exists():
        click.confirm(f"File already exists: {dest}\nOverwrite?", abort=True)

    dest.write_text(code, encoding="utf-8")
    click.echo(f"Created: {dest}")

    # Import hint relative to CWD
    cwd = pathlib.Path.cwd().resolve()
    try:
        import_base = dest.with_suffix("").relative_to(cwd)
        import_str = ".".join(import_base.parts)
    except ValueError:
        import_str = ".".join(rel_path.with_suffix("").parts)

    if framework == "dagster":
        click.echo("\nNext: register in your defs.py:")
        click.echo(f"  import {import_str} as new_mod")
        click.echo("  assets = load_assets_from_modules([..., new_mod])")
    else:
        click.echo(f"\nNext: call  {import_str}.{rel_path.stem.split('_asset')[0] or rel_path.stem}()")
        click.echo("Or import and call the function directly from your pipeline/script.")
