"""pr-agent CLI — scaffold new Dagster ingest asset files."""

import datetime as dt
import pathlib
import re
import sys

import click

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

_HEADER = """\
# EU AI Act Art. 52 — AI-Generated Content
# Generated by: pr-agent scaffold   Date: {date}
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)
"""

_REST_TEMPLATE = _HEADER + """
from dagster import asset, AssetExecutionContext
from pr_automation_agent import BaseRestAsset
import requests


class _{cls}(BaseRestAsset):
    provider = "{provider}"
    entity = "{entity}"

    def fetch_all(self) -> list[dict]:
        # TODO: replace with your real endpoint and auth headers
        r = requests.get(
            "https://api.{provider}.com/{entity}",
            timeout=60,
            # headers={{"Authorization": "Bearer <token>"}},
        )
        r.raise_for_status()
        return r.json()  # TODO: adapt to actual response shape


@asset(group_name="rest_crawl")
def fetch_{provider}_{entity}(context: AssetExecutionContext) -> str:
    return _{cls}().materialize(context)
"""

_GRAPHQL_TEMPLATE = _HEADER + """
from dagster import asset, AssetExecutionContext
from pr_automation_agent import BaseGraphQLAsset


class _{cls}(BaseGraphQLAsset):
    provider = "{provider}"
    entity = "{entity}"
    url = "https://api.{provider}.com/graphql"  # TODO: update URL
    query = \"\"\"
        {{
            {entity}(first: 100) {{
                nodes {{ id name }}            # TODO: match your schema
            }}
        }}
    \"\"\"

    def extract_records(self, data: dict) -> list[dict]:
        # TODO: update this path to match your GraphQL response
        return data["{entity}"]["nodes"]


@asset(group_name="graphql_crawl")
def fetch_{provider}_{entity}(context: AssetExecutionContext) -> str:
    return _{cls}().materialize(context)
"""

_DB_TEMPLATE = _HEADER + """
from dagster import asset, AssetExecutionContext
from pr_automation_agent import BaseDbReplicationAsset


class _{cls}(BaseDbReplicationAsset):
    engine_name = "{engine}"
    table = "{table}"

    def get_query(self, since: str) -> str:
        # TODO: update watermark column name if not updated_at
        return "SELECT * FROM {table} WHERE updated_at >= :since"


@asset(group_name="db_replication", required_resource_keys={{"secret_resolver"}})
def replicate_{engine}_{table}(context: AssetExecutionContext) -> str:
    return _{cls}().materialize(context)
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _to_class_name(*parts: str) -> str:
    return "".join(p.capitalize() for p in parts)


def _safe_id(value: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", value.lower())


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


@click.group()
@click.version_option(package_name="pr-automation-agent")
def cli():
    """pr-automation-agent — scaffold EU AI Act-compliant Dagster ingest assets."""


@cli.command()
@click.argument("asset_type", metavar="TYPE", type=click.Choice(["rest", "graphql", "db"]))
@click.option("--provider", required=True, help="Provider name, e.g. stripe, github, hubspot")
@click.option("--entity", help="Entity/resource name, e.g. invoices, issues (rest/graphql)")
@click.option("--engine", help="DB engine name, e.g. postgres, mysql (db type only)")
@click.option("--table", help="Table name (db type only)")
@click.option(
    "--output-dir",
    default=".",
    show_default=True,
    help="Directory to write the generated file into",
)
@click.option("--dry-run", is_flag=True, help="Print the generated file without writing it")
def scaffold(asset_type, provider, entity, engine, table, output_dir, dry_run):
    """Generate a new Dagster ingest asset file.

    \b
    Examples:
      pr-agent scaffold rest   --provider stripe   --entity invoices
      pr-agent scaffold graphql --provider github  --entity issues
      pr-agent scaffold db     --provider mydb     --engine postgres --table orders
    """
    provider = _safe_id(provider)
    today = dt.date.today().isoformat()

    if asset_type in ("rest", "graphql"):
        if not entity:
            raise click.UsageError("--entity is required for rest and graphql types.")
        entity = _safe_id(entity)

        if asset_type == "rest":
            code = _REST_TEMPLATE.format(
                date=today,
                cls=_to_class_name(provider, entity),
                provider=provider,
                entity=entity,
            )
            rel_path = pathlib.Path("rest") / provider / f"{entity}_asset.py"
        else:
            code = _GRAPHQL_TEMPLATE.format(
                date=today,
                cls=_to_class_name(provider, entity),
                provider=provider,
                entity=entity,
            )
            rel_path = pathlib.Path("graphql") / provider / f"{entity}_asset.py"

    else:  # db
        if not engine:
            raise click.UsageError("--engine is required for db type.")
        if not table:
            raise click.UsageError("--table is required for db type.")
        engine = _safe_id(engine)
        table = _safe_id(table)
        code = _DB_TEMPLATE.format(
            date=today,
            cls=_to_class_name(engine, table),
            engine=engine,
            table=table,
        )
        rel_path = pathlib.Path("db") / engine / f"{table}_replication_asset.py"

    if dry_run:
        click.echo(f"# Would write to: {pathlib.Path(output_dir) / rel_path}\n")
        click.echo(code)
        return

    output_root = pathlib.Path(output_dir).resolve()
    dest = output_root / rel_path
    dest.parent.mkdir(parents=True, exist_ok=True)

    # Create __init__.py only inside output_root, not in output_root itself
    for parent in dest.parents:
        if parent == output_root:
            break
        init = parent / "__init__.py"
        if not init.exists():
            init.touch()

    if dest.exists():
        click.confirm(
            f"File already exists: {dest}\nOverwrite?", abort=True
        )

    dest.write_text(code, encoding="utf-8")
    click.echo(f"Created: {dest}")
    click.echo(f"\nNext: register in your defs.py:")
    click.echo(f"  import {'.'.join(rel_path.with_suffix('').parts)} as new_mod")
    click.echo("  assets = load_assets_from_modules([..., new_mod])")
