# EU AI Act Art. 52 — AI-Generated Content
# Generated by: GitHub Copilot   Template date: 2025-10-03
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)

from dagster import asset, AssetExecutionContext, MetadataValue
from sqlalchemy import create_engine, text
import pandas as pd
import pathlib
import datetime as dt


class _SecretRef:
    def __init__(self, group_name: str, key: str) -> None:
        self.group_name = group_name
        self.key = key


@asset(group_name="db_replication", required_resource_keys={"secret_resolver"})
def replicate_postgres_orders(context: AssetExecutionContext) -> str:
    uri = context.resources.secret_resolver.resolve_as_str(
        _SecretRef(group_name="POSTGRES", key="URI")
    )
    since = context.resources.secret_resolver.resolve_as_str(
        _SecretRef(group_name="POSTGRES", key="SINCE")
    )

    eng = create_engine(uri)
    df = pd.read_sql(
        text("SELECT * FROM orders WHERE updated_at >= :since"),
        eng,
        params={"since": since},
    )

    out = pathlib.Path("warehouse/oso_dagster/tmp/postgres/orders")
    out.mkdir(parents=True, exist_ok=True)
    fp = out / f"{dt.date.today().isoformat()}.parquet"
    df.to_parquet(fp, index=False)

    context.add_output_metadata({
        "rows": MetadataValue.int(len(df)),
        "path": MetadataValue.path(str(fp)),
    })
    return str(fp)
