# EU AI Act Art. 52 — AI-Generated Content
# Generated by: GitHub Copilot   Date: 2025-10-03
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)

from pr_automation_agent import BaseGraphQLFetcher


class _CountriesGraphQL(BaseGraphQLFetcher):
    provider = "countries"
    entity = "countries"
    url = "https://countries.trevorblades.com/"
    query = "{ countries { code name capital } }"

    def extract_records(self, data: dict) -> list[dict]:
        return data["countries"]


def fetch_countries_countries() -> str:
    """Fetch all countries from the Countries GraphQL API. Returns the output path."""
    path, rows = _CountriesGraphQL().run()
    print(f"Wrote {rows} rows to {path}")
    return path


if __name__ == "__main__":
    fetch_countries_countries()
