# EU AI Act Art. 52 — AI-Generated Content
# Generated by: GitHub Copilot   Date: 2025-10-03
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)

from pr_automation_agent import BaseRestFetcher
import requests


class _JSONPlaceholderPosts(BaseRestFetcher):
    provider = "jsonplaceholder"
    entity = "posts"

    def fetch_all(self) -> list[dict]:
        r = requests.get("https://jsonplaceholder.typicode.com/posts", timeout=60)
        r.raise_for_status()
        return r.json()


def fetch_jsonplaceholder_posts() -> str:
    """Fetch posts from JSONPlaceholder and write to disk. Returns the output path."""
    path, rows = _JSONPlaceholderPosts().run()
    print(f"Wrote {rows} rows to {path}")
    return path


if __name__ == "__main__":
    fetch_jsonplaceholder_posts()
