# EU AI Act Art. 52 — AI-Generated Content
# Generated by: GitHub Copilot   Date: 2025-10-03
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)

from dagster import asset, AssetExecutionContext
from pr_automation_agent.integrations.dagster import BaseRestAsset
import requests


class _JSONPlaceholderPosts(BaseRestAsset):
    provider = "jsonplaceholder"
    entity = "posts"

    def fetch_all(self) -> list[dict]:
        r = requests.get("https://jsonplaceholder.typicode.com/posts", timeout=60)
        r.raise_for_status()
        return r.json()


@asset(group_name="rest_crawl")
def fetch_jsonplaceholder_posts(context: AssetExecutionContext) -> str:
    return _JSONPlaceholderPosts().materialize(context)
