# EU AI Act Art. 52 — AI-Generated Content
# Generated by: GitHub Copilot   Date: 2025-10-03
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)

from pr_automation_agent import BaseDbReplicator


class _PostgresOrders(BaseDbReplicator):
    engine_name = "postgres"
    table = "orders"

    def get_query(self, since: str) -> str:
        return "SELECT * FROM orders WHERE updated_at >= :since"


def replicate_postgres_orders() -> str:
    """Replicate orders table incrementally. Returns the output path.

    Requires env vars:
        PR_AGENT__POSTGRES__URI   e.g. sqlite:///demo.db
        PR_AGENT__POSTGRES__SINCE e.g. 1970-01-01
    """
    path, rows = _PostgresOrders().run()
    print(f"Wrote {rows} rows to {path}")
    return path


if __name__ == "__main__":
    replicate_postgres_orders()
