# EU AI Act Art. 52 — AI-Generated Content
# Generated by: GitHub Copilot   Date: 2025-10-03
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)

from dagster import asset, AssetExecutionContext
from pr_automation_agent import BaseDbReplicationAsset


class _PostgresOrders(BaseDbReplicationAsset):
    engine_name = "postgres"
    table = "orders"

    def get_query(self, since: str) -> str:
        return "SELECT * FROM orders WHERE updated_at >= :since"


@asset(group_name="db_replication", required_resource_keys={"secret_resolver"})
def replicate_postgres_orders(context: AssetExecutionContext) -> str:
    return _PostgresOrders().materialize(context)
