# EU AI Act Art. 52 — AI-Generated Content
# Generated by: GitHub Copilot   Date: 2025-10-03
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)

from dagster import asset, AssetExecutionContext
from pr_automation_agent.integrations.dagster import BaseGraphQLAsset


class _CountriesGraphQL(BaseGraphQLAsset):
    provider = "countries"
    entity = "countries"
    url = "https://countries.trevorblades.com/"
    query = "{ countries { code name capital } }"

    def extract_records(self, data: dict) -> list[dict]:
        return data["countries"]


@asset(group_name="graphql_crawl")
def fetch_countries_countries(context: AssetExecutionContext) -> str:
    return _CountriesGraphQL().materialize(context)
