# EU AI Act Art. 52 — AI-Generated Content
# Generated by: GitHub Copilot   Template date: 2025-10-03
# Human reviewer required before merging (see compliance/HUMAN_OVERSIGHT_POLICY.md)

from dagster import asset, AssetExecutionContext, MetadataValue
import requests
import json
import pathlib
import datetime as dt


@asset(group_name="rest_crawl")
def fetch_jsonplaceholder_posts(context: AssetExecutionContext) -> str:
    url = "https://jsonplaceholder.typicode.com/posts"
    r = requests.get(url, timeout=60)
    r.raise_for_status()
    items = r.json()

    out = pathlib.Path("warehouse/oso_dagster/tmp/jsonplaceholder/posts")
    out.mkdir(parents=True, exist_ok=True)
    fp = out / f"{dt.date.today().isoformat()}.json"
    fp.write_text(json.dumps(items))

    context.add_output_metadata({
        "rows": MetadataValue.int(len(items)),
        "path": MetadataValue.path(str(fp)),
    })
    return str(fp)
